### ISSUE TITLE
Would it be possible to remove the cancel on move?

### ISSUE THREAD

**Issue by DLCIncluded** [Thutmose/ThutEssentials#24] opened 2018-03-07 22:50 UTC
Hello there,

We just started using this mod(thanks btw working great), and we were wondering if there was a way to make it not cancel a tp or home on movement.. we are using it on a skyblock pack so it is nice to be able to save yourself and /home or /spawn before you hit y=0. So we found in the config how to make it immediate(no need to wait) but it still cancels if you move or are falling. Is there any way to go about changing this functionality? 

Thanks for any information on the issue!

**Comment by Thutmose** [comment] 2018-03-07 22:52
Try setting the delay to 0 in the config?

**Comment by Thutmose** [comment] 2018-03-07 22:57
Oh, I see, that isn't working, I will see about making delay 0 work as intended

**Comment by DLCIncluded** [comment] 2018-03-07 23:04
Yeah that's what we tried, it does the tp immediately unless you are
falling or moving.. will do more testing tonight if you think that should
work

**Comment by Thutmose** [comment] 2018-03-07 23:07
That was intended to work, but I suspect it might still be having a 1 tick delay, which invalidates the tp when falling, I think I need to specifically check for a 0 tick delay and not deny it in that case.  Unfortunately I am not going to have access to my main pc until Monday, so I won't be able to push a fix for this until then

**Comment by DLCIncluded** [comment] 2018-03-07 23:13
Yeah if it is possible to do with out delay you could add the functionality
to a config option to a Boolean so you can toggle the feature on or off
rather than setting the value to each tp spawn etc to 0. Just a thought
that would be an ease of use type update. We are in no serious rush just
wanted to see if it was something fixable on our end. Let me know if you
get this updated at some point. Thank you for your quick reply by the way!

**Comment by Thutmose** [comment] 2018-03-07 23:15
What I will probably do is a Boolean to make it cancel fall damage, then make the 0 delay work as intended, currently if you are falling and you do manage to to, you will hit the ground too hard

**Comment by Thutmose** [comment] 2018-03-07 23:16
Specifically set this way to prevent people who are falling from saving themselves by tping :D

**Comment by DLCIncluded** [comment] 2018-03-07 23:21
Ah that makes sense, trying to make it less cheaty fair enough

**Comment by Thutmose** [comment] 2018-05-08 02:09
this is now fixed in 2.1.9, which has just been uploaded

**Closed as completed by Thutmose** 2018-05-08 02:09 UTC
